### ISSUE TITLE
About the latest release

### ISSUE THREAD

**Issue by chenrui333** [intel/ittapi#126]
👋 is `3.24.6` the latest release, if so, it looks like the release did not get completed (ie the release notes did not finish). Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/159338

**Comment by chenrui333** [comment]
cc @abrown @ekovanova for thoughts.

**Comment by chenrui333** [comment]
<img width="509" alt="image" src="https://github.com/intel/ittapi/assets/1580956/7c3f7a31-40a0-46b4-9aae-d8b749b912d1">

**Comment by chenrui333** [comment]
also cc @ilya-lavrenov who helped with the formula creation.

**Comment by abrown** [comment]
I pinged @ekovanova about this the other day: my take is that something has changed with the CI job creating releases because both [v3.24.5 and v3.24.6 have failed](https://github.com/intel/ittapi/actions?query=is%3Afailure). What could have changed? The only changes I see in the `release.yml` file are related to the auto-updater that got turned on in #107. Specifically, the auto-generated version bump in #118 looks suspicious because it moves `actions/upload-artifact` from v3.1.3 to v4.0.0, which is a major change. Notice how it is the `upload-artifact` that fails (e.g., [here](https://github.com/intel/ittapi/actions/runs/7451444886/job/20272576175)) in the failing release jobs.

**Comment by abrown** [comment]
This should now be fixed by #144.
