### ISSUE TITLE
Rust ittapi-sys bindings out of date, bindgen-up-to-date.rs possibly broken.

### ISSUE THREAD

**Issue by codecnotsupported** [intel/ittapi#139]
I recently discovered Intel Vtune https://www.intel.com/content/www/us/en/docs/vtune-profiler/user-guide/2024-0/anomaly-detection-analysis.html
It required the following functions to be integrated with the application:
```C
__itt_mark_pt_region_begin(region);
__itt_mark_pt_region_end(region);
```
But they're not available in the rust ittapi(-sys) bindings.
I tried regenerating with `BLESS=1` but the functions didn't show up.
Any chance `bindgen-up-to-date.rs` is broken?

Off note:
Most functions in the public API have a `ITTAPI` which seem to be missing here for both of these functions. Not sure if this is relevant or problematic.

**Comment by abrown** [comment]
I think this is a good find. If you notice in the binding-generation code, it doesn't have an `allowlist_function` entry:

https://github.com/intel/ittapi/blob/9fdc83031a22d66ad23dab8865bc0d9331ee6189/rust/ittapi-sys/tests/bindgen-up-to-date.rs#L33-L35

When I add `.allowlist_function("__itt.*")` in there, I see many more functions now present in the bindings, including the ones you mention. But now I'm wondering why I didn't add that in the first place (@ekovanova, were we supposed to use the pointer versions like `__itt_*_ptr__3_0` instead?).

@codecnotsupported, a couple more questions:
- this statement is unclear to me: "It required the following functions to be integrated with the application." Do you mean that your application failed to compile or it failed to run inside VTune? Or just that you were not able to in fact mark the regions because the API is not yet available in the Rust bindings?
- are you using `ittapi-sys` directly? Or do you want to get these `mark` functions in to the high-level bindings?
- this statement is also confusing me: "Most functions in the public API have a ITTAPI which seem to be missing here for both of these functions." What do you mean by that?

Thanks again for the report!

**Comment by codecnotsupported** [comment]
>this statement is unclear to me: "It required the following functions to be integrated with the application." Do you mean that your application failed to compile or it failed to run inside VTune? Or just that you were not able to in fact mark the regions because the API is not yet available in the Rust bindings?

The latter.

>are you using ittapi-sys directly? Or do you want to get these mark functions in to the high-level bindings?

I was using ittapi-sys directly because there wasn't a high-level API binding. High-level bindings would be preferred.
 
>this statement is also confusing me: "Most functions in the public API have a ITTAPI which seem to be missing here for both of these functions." What do you mean by that?

In `ittnotify.h`, most public API functions are prefixed with `ITTAPI` and `__itt_mark_pt_region_begin/end` seems to be a exception.
I have no clue what the  `ITTAPI` prefix does. I am merely denoting this anomaly just in case it means something to you.
